# Generated by Django 5.2.2 on 2025-07-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bankaccount_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cvv_real',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='pan_real',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
