# Generated by Django 5.2.2 on 2025-07-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_card_cvv_real_card_pan_real'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='balance',
        ),
    ]
