# Generated by Django 5.2.2 on 2025-07-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bankaccount_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='pin',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
