# Generated by Django 5.2.2 on 2025-07-21 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accredito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text="Data dell'accredito")),
                ('amount', models.DecimalField(decimal_places=2, help_text="Importo dell'accredito", max_digits=12)),
                ('currency', models.CharField(default='EUR', help_text='ISO 4217', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(help_text="Origine dell'accredito (es. datore di lavoro, merchant)", max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Annotazioni libere')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrediti', to='accounts.bankaccount')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
