# Generated by Django 5.2.2 on 2025-07-28 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accredito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstrattoConto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mese', models.PositiveSmallIntegerField()),
                ('anno', models.PositiveSmallIntegerField()),
                ('saldo_iniziale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_finale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estratti_conto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-anno', '-mese'],
                'unique_together': {('user', 'mese', 'anno')},
            },
        ),
    ]
