# Generated by Django 5.2.2 on 2025-07-28 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_estrattoconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrattoconto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
