# Generated by Django 5.2.2 on 2025-07-30 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_estrattoconto_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalsSaving',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text="Nome dell'obiettivo (es. Vacanze, Sport, Auto)", max_length=120)),
                ('importo_target', models.DecimalField(decimal_places=2, help_text='Importo obiettivo da raggiungere', max_digits=12)),
                ('importo_attuale', models.DecimalField(decimal_places=2, default=0, help_text='Importo attualmente risparmiato', max_digits=12)),
                ('data_limite', models.DateField(blank=True, help_text="Data limite per raggiungere l'obiettivo (facoltativo)", null=True)),
                ('periodicita', models.CharField(blank=True, choices=[('WEEKLY', 'Settimanale'), ('MONTHLY', 'Mensile'), ('QUARTERLY', 'Trimestrale'), ('BIANNUAL', 'Semestrale'), ('YEARLY', 'Annuale')], help_text='Frequenza del versamento (facoltativo)', max_length=10)),
                ('importo_periodicita', models.DecimalField(blank=True, decimal_places=2, help_text='Importo da versare per ogni periodo', max_digits=12, null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_saving', to='accounts.bankaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('bank_account', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='GoalsSavingMovimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('DEPOSIT', 'Versamento'), ('WITHDRAWAL', 'Prelievo')], max_length=10)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descrizione', models.TextField(blank=True)),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti', to='accounts.goalssaving')),
            ],
            options={
                'ordering': ['-data_movimento'],
            },
        ),
    ]
