# Generated by Django 5.2.2 on 2025-07-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_goalssaving_goalssavingmovimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalssaving',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='goalssaving',
            old_name='created_at',
            new_name='created',
        ),
    ]
