# Generated by Django 5.2.2 on 2025-07-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_goalssaving_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalssaving',
            name='colore',
            field=models.CharField(choices=[('#3498db', 'Blu'), ('#2ecc71', 'Verde'), ('#e74c3c', 'Rosso'), ('#f39c12', 'Arancione'), ('#9b59b6', 'Viola'), ('#1abc9c', 'Turchese'), ('#e91e63', 'Rosa'), ('#3f51b5', 'Indaco')], default='#3498db', help_text="Colore dell'obiettivo per la visualizzazione", max_length=7),
        ),
    ]
