# Generated by Django 5.2.2 on 2025-07-07 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Data della transazione')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Importo positivo per entrate, negativo per uscite', max_digits=12)),
                ('currency', models.CharField(default='EUR', help_text='ISO 4217', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('has_document', models.BooleanField(default=False, help_text="Se c'è allegato un documento (ricevuta, fattura, ecc.)")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp di creazione in DB')),
                ('merchant_name', models.CharField(blank=True, help_text='Nome del merchant o controparte', max_length=255)),
                ('external_id', models.CharField(blank=True, help_text='ID esterno (es. da importazioni batch)', max_length=100, null=True, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Annotazioni libere')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.accounts')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.category')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
