# Generated by Django 5.2.2 on 2025-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='clausola',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destinatario_citta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destinatario_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destinatario_iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destinatario_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='id_transazione',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mittente_citta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mittente_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mittente_iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mittente_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stato',
            field=models.CharField(default='Completata', max_length=32),
        ),
    ]
